classDiagram
    class Playfield {
        +Bille bille
        +Flipper[] flippers
        +Bumper[] bumpers
        +rendu()
        +gererPhysique()
    }

    class Bille {
        +Vector3 position
        +Vector3 vitesse
        +appliquerForce()
        +reinitialiser()
    }

    class Flipper {
        +string cote
        +bool estActif
        +activer()
        +desactiver()
    }

    class Bumper {
        +Vector3 position
        +int valeurPoints
        +declencher()
    }

    class Capacite {
        +string nom
        +string type
        +int cooldownMs
        +bool estActive
        +activer()
        +desactiver()
    }

    class Personnage {
        +string nom
        +Capacite bonus
        +Capacite malus
        +activerBonus()
        +activerMalus()
    }

    class Boss {
        +string nom
        +int hp
        +int hpMax
        +Capacite malus
        +prendreDegats(int)
        +appliquerMalus()
        +estVaincu() bool
    }

    class Joueur {
        +string id
        +Personnage personnage
        +int vies
        +int score
        +float barreUltime
        +ajouterPoints(int)
        +perdreBille()
        +chargerUltime(float)
    }

    class Serveur {
        +Room[] rooms
        +diffuserEvenement()
        +creerRoom()
    }

    class Room {
        +string code
        +string mode
        +Joueur[] joueurs
        +EtatJeu etat
        +rejoindre()
        +quitter()
    }

    class EtatJeu {
        +string statut
        +Boss bossActuel
        +int indexBoss
        +mettreAJour()
        +estFinDePartie() bool
        +calculerXP() int
    }

    Playfield *-- Bille
    Playfield *-- Flipper
    Playfield *-- Bumper
    Playfield --> Joueur
    Joueur --> Personnage
    Personnage *-- Capacite
    Boss *-- Capacite
    Serveur *-- Room
    Room *-- EtatJeu
    Room --> Joueur
    EtatJeu --> Boss

%%  Alexis Gontier - v1.1.0 - 23/02/26
